### ISSUE TITLE
Error on linking

### ISSUE THREAD

**Issue by bencz** [msharov/cobcy#5] opened 2021-02-05 16:26 UTC
Hi
I'm getting this error while building the project on Debian 

> 
> Linking .o/cobcy ...
> /usr/bin/ld: .o/main.o: in function `main':
> main.cc:(.text.startup+0x98): undefined reference to `__cxa_guard_acquire'
> /usr/bin/ld: main.cc:(.text.startup+0xac): undefined reference to `__cxa_guard_release'
> /usr/bin/ld: .o/semconio.o: in function `SetDisplayOutput()':
> semconio.cc:(.text+0x7c): undefined reference to `__dynamic_cast'
> /usr/bin/ld: .o/semconio.o: in function `CobolData const* LookupIdentifier<CobolData>(ustl::string const&)':
> semconio.cc:(.text._Z16LookupIdentifierI9CobolDataEPKT_RKN4ustl6stringE[_Z16LookupIdentifierI9CobolDataEPKT_RKN4ustl6stringE]+0x50): undefined reference to `__dynamic_cast'
> /usr/bin/ld: .o/semcontrol.o: in function `auto SymbolTable::lookup<CobolLabel>(ustl::string const&) const':
> semcontrol.cc:(.text._ZNK11SymbolTable6lookupI10CobolLabelEEDaRKN4ustl6stringE[_ZNK11SymbolTable6lookupI10CobolLabelEEDaRKN4ustl6stringE]+0x38): undefined reference to `__dynamic_cast'
> /usr/bin/ld: .o/semdecl.o: in function `auto SymbolTable::lookup<CobolVar>(ustl::string const&) const':
> semdecl.cc:(.text._ZNK11SymbolTable6lookupI8CobolVarEEDaRKN4ustl6stringE[_ZNK11SymbolTable6lookupI8CobolVarEEDaRKN4ustl6stringE]+0x38): undefined reference to `__dynamic_cast'
> /usr/bin/ld: .o/semfile.o: in function `FileWriteSetup(CobolData const*&)':
> semfile.cc:(.text+0x80): undefined reference to `__dynamic_cast'
> /usr/bin/ld: .o/semfile.o:semfile.cc:(.text+0xb4): more undefined references to `__dynamic_cast' follow
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:29: .o/cobcy] Error 1
> 

g++ version:
> g++ (Debian 10.2.1-6) 10.2.1 20210110
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by msharov** [comment] 2021-02-05 21:01
Fixed by commit 7366ab143d9bd0f48c59931c0c58529eb5179c27 in uSTL.

The problem is that you are using a shared uSTL library, which does not internally use all of libsupc++ that it statically links to. Since there is no shared libsupc++, cobcy would have to link with libsupc++ as well, which removes any possible advantage of having a shared ustl library in the first place. uSTL must therefore only be a static library as well. The above commit disables the building of the shared library.

To upgrade and fix your problem, run `make uninstall` in uSTL first, then pull in the above commit, rebuild and reinstall. This should remove libustl.so and link cobcy with the static libustl.a and libsupc++.a instead, via pkg-config settings.

**Closed by msharov** 2021-02-05 21:01 UTC
